// Converts the SVGs in assets/icons into themeable icon data for <Icon />.
// Run with `npm run icons` after adding or changing an icon.
//
// Expected input (Figma export): 24×24 viewBox, shapes drawn in black,
// details that should be cut out drawn in white, an optional white 24×24
// background rect, optional clip-path wrappers. Background and wrappers are
// dropped; black becomes the icon color, white becomes a cut-out.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const SOURCE_DIR = join(ROOT, "assets/icons");
const OUTPUT_FILE = join(ROOT, "src/constants/icons.generated.ts");

const SHAPES = new Set(["path", "circle", "rect"]);
const ATTRIBUTES = {
  d: "d",
  cx: "cx",
  cy: "cy",
  r: "r",
  x: "x",
  y: "y",
  width: "width",
  height: "height",
  rx: "rx",
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
};

function paint(value, file) {
  if (value === undefined || value === "none") return undefined;
  if (value === "black" || value === "#000" || value === "#000000") return "on";
  if (value === "white" || value === "#fff" || value === "#FFFFFF")
    return "off";
  throw new Error(`${file}: unsupported color "${value}" (use black or white)`);
}

function parseIcon(file) {
  const svg = readFileSync(join(SOURCE_DIR, file), "utf8");
  if (!svg.includes('viewBox="0 0 24 24"')) {
    throw new Error(`${file}: expected a 24×24 viewBox`);
  }
  // Clip paths only frame the 24×24 canvas, so their contents are skipped.
  // Masks are Figma's "inside"/"outside" strokes; their shapes aren't drawn
  const body = svg
    .replace(/<defs>[\s\S]*?<\/defs>/g, "")
    .replace(/<mask[\s\S]*?<\/mask>/g, "");
  const elements = [];

  for (const [, tag, rawAttrs] of body.matchAll(/<(\w+)\s([^>]*?)\/?>/g)) {
    if (!SHAPES.has(tag)) continue;
    const attrs = Object.fromEntries(
      [...rawAttrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, k, v]) => [k, v]),
    );
    const isBackground =
      tag === "rect" &&
      attrs.width === "24" &&
      attrs.height === "24" &&
      !attrs.x &&
      !attrs.y &&
      !attrs.stroke;
    if (isBackground) continue;
    // A masked stroke can't be drawn without its mask: skip it, so it doesn't
    // spill outside its shape. Use centre strokes (or Outline stroke) in Figma
    if (attrs.mask) {
      console.warn(`${file}: skipped a masked shape (inside/outside stroke)`);
      continue;
    }

    const element = { type: tag };
    for (const [svgName, propName] of Object.entries(ATTRIBUTES)) {
      if (attrs[svgName] === undefined) continue;
      const numeric = Number(attrs[svgName]);
      element[propName] =
        Number.isNaN(numeric) || svgName === "d" ? attrs[svgName] : numeric;
    }
    const fill = paint(attrs.fill, file);
    const stroke = paint(attrs.stroke, file);
    if (fill) element.fill = fill;
    if (stroke) element.stroke = stroke;
    elements.push(element);
  }

  if (elements.length === 0) throw new Error(`${file}: no shapes found`);
  const knockout = elements.some((e) => e.fill === "off" || e.stroke === "off");
  return { name: basename(file, ".svg"), knockout, elements };
}

const icons = readdirSync(SOURCE_DIR)
  .filter((file) => file.endsWith(".svg"))
  .sort()
  .map(parseIcon);

const entries = icons
  .map(
    ({ name, knockout, elements }) =>
      `  ${JSON.stringify(name)}: { knockout: ${knockout}, elements: ${JSON.stringify(elements)} },`,
  )
  .join("\n");

writeFileSync(
  OUTPUT_FILE,
  `// Generated by scripts/generate-icons.mjs from assets/icons — do not edit.

import type { IconData } from "@/components/icon";

export const Icons = {
${entries}
} satisfies Record<string, IconData>;

export type IconName = keyof typeof Icons;
`,
);

console.log(
  `Generated ${icons.length} icons → src/constants/icons.generated.ts`,
);
