// Generated by scripts/generate-icons.mjs from assets/icons — do not edit.

import type { IconData } from "@/components/ui/icon";

export const Icons = {
  "activity.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 2C19.3137 2 22 4.68629 22 8V16C22 19.3137 19.3137 22 16 22H8C4.68629 22 2 19.3137 2 16V8C2 4.68629 4.68629 2 8 2H16ZM17.8574 10.4854C17.5732 10.0119 16.9589 9.85846 16.4854 10.1426L14.1816 11.5254C13.865 11.7153 13.469 11.7153 13.1523 11.5254L11.877 10.7598C10.927 10.1898 9.74005 10.1899 8.79004 10.7598L6.48535 12.1426C6.01188 12.4268 5.85846 13.0411 6.14258 13.5146C6.42676 13.9881 7.04112 14.1415 7.51465 13.8574L9.81836 12.4746C10.135 12.2846 10.531 12.2847 10.8477 12.4746L12.123 13.2402C13.073 13.8102 14.2599 13.8101 15.21 13.2402L17.5146 11.8574C17.9881 11.5732 18.1415 10.9589 17.8574 10.4854Z",
        fill: "on",
      },
    ],
  },
  activity: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 3H8C5.23858 3 3 5.23858 3 8V16C3 18.7614 5.23858 21 8 21H16C18.7614 21 21 18.7614 21 16V8C21 5.23858 18.7614 3 16 3Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 13L9.30434 11.6174C9.93771 11.2374 10.729 11.2374 11.3623 11.6174L12.6377 12.3826C13.271 12.7626 14.0623 12.7626 14.6957 12.3826L17 11",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "archive.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M20 4C21.2436 4 22 5.12055 22 6.16699V8.5C22 9.27043 21.6285 10.0251 21.4072 10.501C21.1285 11.1004 21 11.4214 21 11.6592V17.833C21 18.8794 20.2436 20 19 20H5C3.75636 20 3 18.8794 3 17.833V11.6592C2.99995 11.4214 2.87146 11.1004 2.59277 10.501C2.3715 10.0251 2 9.27043 2 8.5V6.16699C2 5.12055 2.75637 4 4 4H20ZM8 9C7.44772 9 7 9.44772 7 10C7 10.5523 7.44772 11 8 11H16C16.5523 11 17 10.5523 17 10C17 9.44772 16.5523 9 16 9H8Z",
        fill: "on",
      },
    ],
  },
  archive: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M20 11.6593V17.8333C20 18.4777 19.5523 19 19 19H5C4.44772 19 4 18.4777 4 17.8333V11.6593C4 10.6509 3 9.50846 3 8.5V6.16667C3 5.52233 3.44772 5 4 5H20C20.5523 5 21 5.52233 21 6.16667V8.5C21 9.50846 20 10.6509 20 11.6593Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M8 10H16",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.down": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 20L20 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20L4 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20L12 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.left.arrow.right": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 12L7 9",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12L7 15",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12H10",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12L17 9",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12L17 15",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12H14",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.left": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 12L12 20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12L12 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12H20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.right": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M20 12L12 20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12L12 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12H4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.up.arrow.down": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 4L15 7",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L9 7",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L12 10",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20L15 17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20L9 17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20V14",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "arrow.up": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 4L20 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L4 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L12 20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "bell.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16.1459 17H7.8541C5.62395 17 4.17347 14.6531 5.17082 12.6584L8.17081 6.65836C8.67899 5.64201 9.71778 5 10.8541 5H13.1459C14.2822 5 15.321 5.64201 15.8292 6.65836L18.8292 12.6584C19.8265 14.6531 18.376 17 16.1459 17Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        fill: "on",
        stroke: "on",
      },
      {
        type: "path",
        d: "M13.5024 19H10.4975C9.62629 19 9.34902 20.1745 10.1283 20.5642C10.7015 20.8508 11.3336 21 11.9745 21H12.0254C12.6663 21 13.2984 20.8508 13.8717 20.5642C14.6509 20.1745 14.3737 19 13.5024 19Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M11 4H13",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  bell: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16.1459 17H7.8541C5.62395 17 4.17347 14.6531 5.17082 12.6584L8.17081 6.65836C8.67899 5.64201 9.71778 5 10.8541 5H13.1459C14.2822 5 15.321 5.64201 15.8292 6.65836L18.8292 12.6584C19.8265 14.6531 18.376 17 16.1459 17Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M13.5024 19H10.4975C9.62629 19 9.34902 20.1745 10.1283 20.5642C10.7015 20.8508 11.3336 21 11.9745 21H12.0254C12.6663 21 13.2984 20.8508 13.8717 20.5642C14.6509 20.1745 14.3737 19 13.5024 19Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M11 4H13",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "bookmark.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M15 3H9C7.34315 3 6 4.34315 6 6V19.2251C6 20.5903 7.33739 21.5542 8.63246 21.1225L11.3675 20.2108C11.7781 20.074 12.2219 20.074 12.6325 20.2108L15.3675 21.1225C16.6626 21.5542 18 20.5903 18 19.2251V6C18 4.34315 16.6569 3 15 3Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  bookmark: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M15 3H9C7.34315 3 6 4.34315 6 6V19.2251C6 20.5903 7.33739 21.5542 8.63246 21.1225L11.3675 20.2108C11.7781 20.074 12.2219 20.074 12.6325 20.2108L15.3675 21.1225C16.6626 21.5542 18 20.5903 18 19.2251V6C18 4.34315 16.6569 3 15 3Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "calendar.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 2C19.3137 2 22 4.68629 22 8V16C22 19.3137 19.3137 22 16 22H8C4.68629 22 2 19.3137 2 16V8C2 4.68629 4.68629 2 8 2H16ZM7 6C6.44772 6 6 6.44772 6 7C6 7.55228 6.44772 8 7 8H17C17.5523 8 18 7.55228 18 7C18 6.44772 17.5523 6 17 6H7Z",
        fill: "on",
      },
    ],
  },
  calendar: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 21H8C5.23858 21 3 18.7614 3 16V8C3 5.23858 5.23858 3 8 3H16C18.7614 3 21 5.23858 21 8V16C21 18.7614 18.7614 21 16 21Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 7H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "checkmark.circle.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3ZM15.5664 8.17578C15.1113 7.86304 14.4886 7.97854 14.1758 8.43359L10.7549 13.4102L9.72949 12.3164C9.35181 11.9135 8.71933 11.8929 8.31641 12.2705C7.91355 12.6482 7.89294 13.2807 8.27051 13.6836L9.7207 15.2305C10.3756 15.929 11.5082 15.8437 12.0508 15.0547L15.8242 9.56641C16.137 9.11132 16.0215 8.48863 15.5664 8.17578Z",
        fill: "on",
      },
    ],
  },
  "checkmark.circle": {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 8, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M9 13L10.4501 14.5468C10.6684 14.7797 11.0461 14.7511 11.2269 14.4881L15 9",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  checkmark: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 15L8.57496 19.575C8.79601 19.796 9.16343 19.7623 9.34054 19.5047L20 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.down": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 16L20 8",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 16L4 8",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.left.chevron.right": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M20 12L14.4615 7.00002",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20 12L14.4615 17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12L9.53846 7.00002",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M4 12L9.53846 17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.left": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M8 12L16 20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M8 12L16 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.right": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 12L8 20",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M16 12L8 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.up.chevron.down": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 20L17 14.4615",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 20L7 14.4615",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L17 9.53846",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 4L7 9.53846",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "chevron.up": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 8L20 16",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 8L4 16",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "circle.fill.half": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M3 12C3 16.6326 6.50005 20.4476 11 20.9451V3.05493C6.50005 3.55237 3 7.36745 3 12Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M11 3.05493C6.50005 3.55237 3 7.36745 3 12C3 16.6326 6.50005 20.4476 11 20.9451C11.3283 20.9814 11.662 21 12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C11.662 3 11.3283 3.01863 11 3.05493ZM11 20.9451V3.05493",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  circle: {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 9, strokeWidth: 2, stroke: "on" },
    ],
  },
  "ellipsis.circle.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M11.9756 2.94531C16.9901 2.94558 21.0557 7.01078 21.0557 12.0254C21.0554 17.0398 16.99 21.1052 11.9756 21.1055C6.96098 21.1055 2.89577 17.0399 2.89551 12.0254C2.89551 7.01062 6.96081 2.94531 11.9756 2.94531ZM8 10.5254C7.17157 10.5254 6.5 11.197 6.5 12.0254C6.50026 12.8536 7.17174 13.5254 8 13.5254C8.82826 13.5254 9.49974 12.8536 9.5 12.0254C9.5 11.197 8.82843 10.5254 8 10.5254ZM12 10.5254C11.1716 10.5254 10.5 11.197 10.5 12.0254C10.5003 12.8536 11.1717 13.5254 12 13.5254C12.8282 13.5254 13.4997 12.8536 13.5 12.0254C13.5 11.197 12.8284 10.5254 12 10.5254ZM16 10.5254C15.1716 10.5254 14.5 11.197 14.5 12.0254C14.5003 12.8536 15.1717 13.5254 16 13.5254C16.8282 13.5253 17.4997 12.8536 17.5 12.0254C17.5 11.197 16.8284 10.5254 16 10.5254Z",
        fill: "on",
      },
    ],
  },
  "ellipsis.circle": {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 8, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M8 12H8.0001",
        strokeWidth: 3,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M11.9999 12H12",
        strokeWidth: 3,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M15.9999 12H16",
        strokeWidth: 3,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  ellipsis: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6 12H6.0001",
        strokeWidth: 4,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M11.9999 12H12",
        strokeWidth: 4,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M17.9999 12H18",
        strokeWidth: 4,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "gear.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M10.6582 2.55242C11.5027 2.13022 12.4973 2.13022 13.3418 2.55242L19.3418 5.55242C20.358 6.06057 20.9999 7.09986 21 8.23602V15.7634C21 16.8996 20.358 17.9387 19.3418 18.447L13.3418 21.447C12.4972 21.8692 11.5028 21.8692 10.6582 21.447L4.6582 18.447C3.64199 17.9387 3 16.8996 3 15.7634V8.23602C3.00012 7.09986 3.64201 6.06057 4.6582 5.55242L10.6582 2.55242ZM12 8.99969C10.3432 8.99969 9.00017 10.343 9 11.9997C9 13.6565 10.3431 14.9997 12 14.9997C13.6569 14.9997 15 13.6565 15 11.9997C14.9998 10.343 13.6568 8.99969 12 8.99969Z",
        fill: "on",
      },
    ],
  },
  gear: {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 2, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M18.8944 6.44721L12.8944 3.44721C12.3314 3.16569 11.6686 3.16569 11.1056 3.44721L5.10557 6.44721C4.428 6.786 4 7.47852 4 8.23606V15.7639C4 16.5215 4.42801 17.214 5.10557 17.5528L11.1056 20.5528C11.6686 20.8343 12.3314 20.8343 12.8944 20.5528L18.8944 17.5528C19.572 17.214 20 16.5215 20 15.7639V8.23607C20 7.47852 19.572 6.78599 18.8944 6.44721Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "heart.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M18.8552 13.1448L12.7071 19.2929C12.3166 19.6834 11.6834 19.6834 11.2929 19.2929L5.14478 13.1448C3.84363 11.8436 3.4431 9.89226 4.12649 8.18377L4.27335 7.81662C4.72969 6.67578 5.70611 5.82347 6.89814 5.52547C8.20213 5.19947 9.58155 5.58155 10.532 6.53198L11.2929 7.29289C11.6834 7.68342 12.3166 7.68342 12.7071 7.29289L13.468 6.53198C14.4185 5.58155 15.7979 5.19947 17.1019 5.52547C18.2939 5.82347 19.2703 6.67578 19.7266 7.81661L19.8735 8.18377C20.5569 9.89226 20.1564 11.8436 18.8552 13.1448Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        fill: "on",
        stroke: "on",
      },
    ],
  },
  heart: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M18.8552 13.1448L12.7071 19.2929C12.3166 19.6834 11.6834 19.6834 11.2929 19.2929L5.14478 13.1448C3.84363 11.8436 3.4431 9.89226 4.12649 8.18377L4.27335 7.81662C4.72969 6.67578 5.70611 5.82347 6.89814 5.52547C8.20213 5.19947 9.58155 5.58155 10.532 6.53198L11.2929 7.29289C11.6834 7.68342 12.3166 7.68342 12.7071 7.29289L13.468 6.53198C14.4185 5.58155 15.7979 5.19947 17.1019 5.52547C18.2939 5.82347 19.2703 6.67578 19.7266 7.81661L19.8735 8.18377C20.5569 9.89226 20.1564 11.8436 18.8552 13.1448Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "home.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 21H8C5.23858 21 3 18.7614 3 16V11.3201C3 9.75754 3.73051 8.28481 4.97458 7.33931L8.97458 4.29932C10.7626 2.9404 13.2374 2.9404 15.0254 4.29932L19.0254 7.33931C20.2695 8.28481 21 9.75754 21 11.3201V16C21 18.7614 18.7614 21 16 21Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  home: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 21H8C5.23858 21 3 18.7614 3 16V11.3201C3 9.75754 3.73051 8.28481 4.97458 7.33931L8.97458 4.29932C10.7626 2.9404 13.2374 2.9404 15.0254 4.29932L19.0254 7.33931C20.2695 8.28481 21 9.75754 21 11.3201V16C21 18.7614 18.7614 21 16 21Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "info.circle.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM12 10C11.4477 10 11 10.4477 11 11V17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17V11C13 10.4477 12.5523 10 12 10ZM12 5.75C11.3096 5.75 10.75 6.30964 10.75 7C10.75 7.69036 11.3096 8.25 12 8.25C12.6904 8.25 13.25 7.69036 13.25 7C13.25 6.30964 12.6904 5.75 12 5.75Z",
        fill: "on",
      },
    ],
  },
  "info.circle": {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 9, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M12 11V17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 7V7.0001",
        strokeWidth: 2.5,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "line.2.horizontal": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M9 16H21",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M3 8H21",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "line.3.horizontal.decrease": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6 12L18 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M3 7L21 7",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M10 17H14",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "line.3.horizontal.square.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 2C19.3137 2 22 4.68629 22 8V16C22 19.3137 19.3137 22 16 22H8C4.68629 22 2 19.3137 2 16V8C2 4.68629 4.68629 2 8 2H16ZM7 15C6.44772 15 6 15.4477 6 16C6 16.5523 6.44772 17 7 17H11C11.5523 17 12 16.5523 12 16C12 15.4477 11.5523 15 11 15H7ZM7 11C6.44772 11 6 11.4477 6 12C6 12.5523 6.44772 13 7 13H17C17.5523 13 18 12.5523 18 12C18 11.4477 17.5523 11 17 11H7ZM7 7C6.44772 7 6 7.44772 6 8C6 8.55228 6.44772 9 7 9H13C13.5523 9 14 8.55228 14 8C14 7.44772 13.5523 7 13 7H7Z",
        fill: "on",
      },
    ],
  },
  "line.3.horizontal.square": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 3H8C5.23858 3 3 5.23858 3 8V16C3 18.7614 5.23858 21 8 21H16C18.7614 21 21 18.7614 21 16V8C21 5.23858 18.7614 3 16 3Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 8H13",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 12H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 16H11",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "line.3.horizontal": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M3 6H15",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M3 12H21",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M3 18H11",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  link: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6.5 14H6C4.34315 14 3 12.6569 3 11C3 9.34315 4.34315 8 6 8H12C13.6569 8 15 9.34315 15 11C15 12.6569 13.6569 14 12 14",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 11C10.3431 11 9 12.3431 9 14C9 15.6569 10.3431 17 12 17H18C19.6569 17 21 15.6569 21 14C21 12.3431 19.6569 11 18 11H17.5",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "list.bullet.square.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 2C19.3137 2 22 4.68629 22 8V16C22 19.3137 19.3137 22 16 22H8C4.68629 22 2 19.3137 2 16V8C2 4.68629 4.68629 2 8 2H16ZM7 15C6.44772 15 6 15.4477 6 16C6 16.5523 6.44772 17 7 17H8C8.55228 17 9 16.5523 9 16C9 15.4477 8.55228 15 8 15H7ZM11 15C10.4477 15 10 15.4477 10 16C10 16.5523 10.4477 17 11 17H17C17.5523 17 18 16.5523 18 16C18 15.4477 17.5523 15 17 15H11ZM7 11C6.44772 11 6 11.4477 6 12C6 12.5523 6.44772 13 7 13H8C8.55228 13 9 12.5523 9 12C9 11.4477 8.55228 11 8 11H7ZM11 11C10.4477 11 10 11.4477 10 12C10 12.5523 10.4477 13 11 13H17C17.5523 13 18 12.5523 18 12C18 11.4477 17.5523 11 17 11H11ZM7 7C6.44772 7 6 7.44772 6 8C6 8.55228 6.44772 9 7 9H8C8.55228 9 9 8.55228 9 8C9 7.44772 8.55228 7 8 7H7ZM11 7C10.4477 7 10 7.44772 10 8C10 8.55228 10.4477 9 11 9H17C17.5523 9 18 8.55228 18 8C18 7.44772 17.5523 7 17 7H11Z",
        fill: "on",
      },
    ],
  },
  "list.bullet.square": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 3H8C5.23858 3 3 5.23858 3 8V16C3 18.7614 5.23858 21 8 21H16C18.7614 21 21 18.7614 21 16V8C21 5.23858 18.7614 3 16 3Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M11 8H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M11 12H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M11 16H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 8H8",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 12H8",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 16H8",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "location.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M14.379 5.8263L6.79076 8.3557C4.12062 9.24575 4.03554 12.9914 6.66251 14.0018L7.82717 14.4497C8.61945 14.7545 9.24554 15.3806 9.55027 16.1728L9.99821 17.3375C11.0086 19.9645 14.7543 19.8794 15.6443 17.2092L18.1737 9.62103C18.9555 7.27576 16.7242 5.04454 14.379 5.8263Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  "location.north.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M9.31672 7.36657L5.7396 14.5208C4.48089 17.0382 7.06931 19.747 9.6413 18.6039L10.7816 18.0971C11.5573 17.7523 12.4427 17.7523 13.2184 18.0971L14.3587 18.6039C16.9307 19.747 19.5191 17.0382 18.2604 14.5208L14.6833 7.36656C13.5777 5.15542 10.4223 5.15542 9.31672 7.36657Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  "location.north": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M9.31672 7.36657L5.7396 14.5208C4.48089 17.0382 7.06931 19.747 9.6413 18.6039L10.7816 18.0971C11.5573 17.7523 12.4427 17.7523 13.2184 18.0971L14.3587 18.6039C16.9307 19.747 19.5191 17.0382 18.2604 14.5208L14.6833 7.36656C13.5777 5.15542 10.4223 5.15542 9.31672 7.36657Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  location: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M14.379 5.8263L6.79076 8.3557C4.12062 9.24575 4.03554 12.9914 6.66251 14.0018L7.82717 14.4497C8.61945 14.7545 9.24554 15.3806 9.55027 16.1728L9.99821 17.3375C11.0086 19.9645 14.7543 19.8794 15.6443 17.2092L18.1737 9.62103C18.9555 7.27576 16.7242 5.04454 14.379 5.8263Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "lock.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M17 20H7C5.89543 20 5 19.1046 5 18V14C5 12.8954 5.89543 12 7 12H17C18.1046 12 19 12.8954 19 14V18C19 19.1046 18.1046 20 17 20Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 12V9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9V12",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  lock: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M17 20H7C5.89543 20 5 19.1046 5 18V14C5 12.8954 5.89543 12 7 12H17C18.1046 12 19 12.8954 19 14V18C19 19.1046 18.1046 20 17 20Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 12V9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9V12",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "map.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M7.10254 2.57784C8.33409 2.16735 9.66591 2.16735 10.8975 2.57784L14.1543 3.66378C14.7033 3.84668 15.2967 3.84668 15.8457 3.66378C18.8731 2.65471 21.9998 4.90825 22 8.09933V15.3962C21.9999 17.9786 20.3473 20.2709 17.8975 21.0876L16.8975 21.4216C15.6659 21.8321 14.3341 21.8321 13.1025 21.4216L9.8457 20.3357C9.2968 20.1528 8.7032 20.1528 8.1543 20.3357C5.1268 21.3448 2 19.0914 2 15.9001V8.60323C2.00024 6.02095 3.65278 3.72851 6.10254 2.91183L7.10254 2.57784ZM15 6.99972C14.4478 6.99972 14.0002 7.44756 14 7.99972V17.9997C14 18.552 14.4477 18.9997 15 18.9997C15.5523 18.9997 16 18.552 16 17.9997V7.99972C15.9998 7.44756 15.5522 6.99972 15 6.99972ZM9 4.99972C8.44781 4.99972 8.00015 5.44756 8 5.99972V15.9997C8 16.552 8.44772 16.9997 9 16.9997C9.55228 16.9997 10 16.552 10 15.9997V5.99972C9.99985 5.44756 9.55219 4.99972 9 4.99972Z",
        fill: "on",
      },
    ],
  },
  map: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M13.4189 20.473L10.1623 19.3874C9.40783 19.1359 8.59217 19.1359 7.83772 19.3874C5.45776 20.1807 3 18.4093 3 15.9006V8.6038C3 6.45164 4.37715 4.54095 6.41886 3.86038L7.41886 3.52705C8.4452 3.18493 9.5548 3.18493 10.5811 3.52705L13.8377 4.61257C14.5922 4.86406 15.4078 4.86406 16.1623 4.61257C18.5422 3.81925 21 5.5907 21 8.09941V15.3962C21 17.5484 19.6228 19.4591 17.5811 20.1396L16.5811 20.473C15.5548 20.8151 14.4452 20.8151 13.4189 20.473Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M9 7V15",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M15 9V17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "message.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 4C16.9706 4 21 7.80558 21 12.5V17C21 19.2091 19.2091 21 17 21H12C7.02944 21 3 17.1944 3 12.5C3 7.80558 7.02944 4 12 4Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  message: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 4C16.9706 4 21 7.80558 21 12.5V17C21 19.2091 19.2091 21 17 21H12C7.02944 21 3 17.1944 3 12.5C3 7.80558 7.02944 4 12 4Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  minus: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6 12L18 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "pen.2": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M19.2929 5.29289C19.6834 5.68342 19.6834 6.31658 19.2929 6.70711L6.11506 19.8849C6.03915 19.9608 5.95129 20.0244 5.85529 20.0724L3.34162 21.3293C2.91189 21.544 2.45593 21.0881 2.67072 20.6584L3.92756 18.1447C3.9756 18.0487 4.03916 17.9608 4.11506 17.8849L17.2929 4.70711C17.6834 4.31658 18.3166 4.31658 18.7071 4.70711L19.2929 5.29289Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M19.2928 2.7072C19.6833 2.31669 20.3173 2.31668 20.7078 2.7072L21.2928 3.29314C21.6833 3.68367 21.6833 4.31668 21.2928 4.7072L21.2071 4.79289C20.8166 5.18342 20.1834 5.18342 19.7929 4.79289L19.2071 4.20711C18.8166 3.81658 18.8166 3.18342 19.2071 2.79289L19.2928 2.7072Z",
        fill: "on",
      },
    ],
  },
  pen: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M19.6465 3.06055C19.8417 2.86535 20.1582 2.86547 20.3535 3.06055L20.9395 3.64648C21.1347 3.84175 21.1347 4.15825 20.9395 4.35352L5.76074 19.5312C5.72274 19.5692 5.67892 19.601 5.63086 19.625L3.11816 20.8818L4.375 18.3691C4.39904 18.3211 4.43075 18.2773 4.46875 18.2393L19.6465 3.06055Z",
        fill: "on",
        stroke: "on",
      },
    ],
  },
  "photo.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 4C19.3137 4 22 6.68629 22 10V14C22 17.3137 19.3137 20 16 20H8C4.68629 20 2 17.3137 2 14V10C2 6.68629 4.68629 4 8 4H16ZM17.8213 12.1719C16.7448 10.2891 14.087 10.1355 12.8008 11.8818L11.7197 13.3496C11.4499 13.7157 10.9166 13.7539 10.5977 13.4297C9.48193 12.2936 7.63477 12.3446 6.58398 13.541L4.70605 15.6807C3.57165 16.9731 4.4892 19 6.20898 19H18.2764C19.8118 19 20.775 17.341 20.0137 16.0078L17.8213 12.1719ZM9 7C7.89543 7 7 7.89543 7 9C7 10.1046 7.89543 11 9 11C10.1046 11 11 10.1046 11 9C11 7.89543 10.1046 7 9 7Z",
        fill: "on",
      },
      {
        type: "rect",
        x: 3,
        y: 5,
        width: 18,
        height: 14,
        rx: 5,
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "photo.slash.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M7.91016 7.32422C7.36263 7.68103 7 8.29773 7 9C7 10.1046 7.89543 11 9 11C9.70237 11 10.318 10.6365 10.6748 10.0889L12.6592 12.0732L11.7197 13.3496C11.4499 13.7159 10.9166 13.754 10.5977 13.4297C9.48189 12.2933 7.63481 12.3443 6.58398 13.541L4.70605 15.6807C3.57149 16.9731 4.48913 19 6.20898 19H18.2764C18.661 19 19.009 18.8948 19.3037 18.7178L19.4746 18.8887C18.4938 19.587 17.2957 20 16 20H8C4.68629 20 2 17.3137 2 14V10C2 7.67686 3.32077 5.66297 5.25195 4.66602L7.91016 7.32422ZM16 4C19.3137 4 22 6.68629 22 10V14C22 15.2957 21.587 16.4938 20.8887 17.4746L20.2734 16.8594C20.2533 16.5733 20.1712 16.2835 20.0137 16.0078L17.8213 12.1719C17.0655 10.8496 15.5302 10.3809 14.2373 10.8232L7.44043 4.02637C7.62468 4.00932 7.8113 4 8 4H16Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M6.77637 6.19043C5.16571 6.70736 4 8.21763 4 10V14C4 16.2091 5.79086 18 8 18H16C16.7417 18 17.4358 17.7971 18.0312 17.4453L19.4746 18.8887C18.4938 19.587 17.2957 20 16 20H8C4.68629 20 2 17.3137 2 14V10C2 7.67686 3.32077 5.66297 5.25195 4.66602L6.77637 6.19043ZM16 4C19.3137 4 22 6.68629 22 10V14C22 15.2957 21.587 16.4938 20.8887 17.4746L19.4453 16.0312C19.7971 15.4358 20 14.7417 20 14V10C20 7.79086 18.2091 6 16 6H9.41406L7.44043 4.02637C7.62468 4.00932 7.8113 4 8 4H16Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M3 3L21 21",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "photo.slash": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6.77637 6.19043C5.16571 6.70736 4 8.21763 4 10V14C4 16.2091 5.79086 18 8 18H16C16.7417 18 17.4358 17.7971 18.0312 17.4453L19.4746 18.8887C18.4938 19.587 17.2957 20 16 20H8C4.68629 20 2 17.3137 2 14V10C2 7.67686 3.32077 5.66297 5.25195 4.66602L6.77637 6.19043ZM16 4C19.3137 4 22 6.68629 22 10V14C22 15.2957 21.587 16.4938 20.8887 17.4746L19.4453 16.0312C19.7971 15.4358 20 14.7417 20 14V10C20 7.79086 18.2091 6 16 6H9.41406L7.44043 4.02637C7.62468 4.00932 7.8113 4 8 4H16Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M9.96289 9.37695C9.78647 10.3012 8.9756 11 8 11C6.89543 11 6 10.1046 6 9C6 8.02467 6.69824 7.21285 7.62207 7.03613L9.96289 9.37695Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M19.3039 18.7177C19.0092 18.8947 18.6611 18.9999 18.2766 18.9999H6.20917C4.48927 18.9999 3.57154 16.973 4.70624 15.6806L6.58417 13.5409C7.63501 12.3443 9.48211 12.2932 10.5978 13.4296C10.9168 13.754 11.4501 13.716 11.7199 13.3495L12.6594 12.0732L19.3039 18.7177ZM14.2375 10.8232C15.5304 10.3809 17.0657 10.8495 17.8215 12.1718L20.0139 16.0077C20.1714 16.2835 20.2535 16.5733 20.2736 16.8593L14.2375 10.8232Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M3 3L21 21",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  photo: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M3 10C3 7.23858 5.23858 5 8 5H16C18.7614 5 21 7.23858 21 10V14C21 16.7614 18.7614 19 16 19H8C5.23858 19 3 16.7614 3 14V10Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "circle",
        cx: 8,
        cy: 9,
        r: 1,
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
      {
        type: "path",
        d: "M18.2768 18H6.20883C5.34885 18 4.88997 16.9864 5.45739 16.3402L7.33564 14.2011C8.00284 13.4412 9.17516 13.4086 9.88361 14.1301C10.6339 14.8944 11.8901 14.8053 12.5251 13.9429L13.6063 12.4746C14.4639 11.3101 16.2358 11.4126 16.9533 12.6683L19.1451 16.5039C19.526 17.1705 19.0446 18 18.2768 18Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        fill: "on",
        stroke: "on",
      },
    ],
  },
  plus: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M6 12L18 12",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M12 6V18",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "rectangle.grid.1x2.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M18 2C20.2091 2 22 3.79086 22 6V7C22 9.20914 20.2091 11 18 11H6C3.79086 11 2 9.20914 2 7V6C2 3.79086 3.79086 2 6 2H18ZM6 3.5C4.61929 3.5 3.5 4.61929 3.5 6V7C3.5 8.38071 4.61929 9.5 6 9.5H18C19.3807 9.5 20.5 8.38071 20.5 7V6C20.5 4.61929 19.3807 3.5 18 3.5H6ZM18 4.5C18.8284 4.5 19.5 5.17157 19.5 6V7C19.5 7.82843 18.8284 8.5 18 8.5H6C5.17157 8.5 4.5 7.82843 4.5 7V6C4.5 5.17157 5.17157 4.5 6 4.5H18Z",
        fill: "on",
      },
      {
        type: "path",
        d: "M18 13C20.2091 13 22 14.7909 22 17V18C22 20.2091 20.2091 22 18 22H6C3.79086 22 2 20.2091 2 18V17C2 14.7909 3.79086 13 6 13H18ZM6 14.5C4.61929 14.5 3.5 15.6193 3.5 17V18C3.5 19.3807 4.61929 20.5 6 20.5H18C19.3807 20.5 20.5 19.3807 20.5 18V17C20.5 15.6193 19.3807 14.5 18 14.5H6ZM18 15.5C18.8284 15.5 19.5 16.1716 19.5 17V18C19.5 18.8284 18.8284 19.5 18 19.5H6C5.17157 19.5 4.5 18.8284 4.5 18V17C4.5 16.1716 5.17157 15.5 6 15.5H18Z",
        fill: "on",
      },
    ],
  },
  "rectangle.grid.1x2": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M18 3H6C4.34315 3 3 4.34315 3 6V7C3 8.65685 4.34315 10 6 10H18C19.6569 10 21 8.65685 21 7V6C21 4.34315 19.6569 3 18 3Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M18 14H6C4.34315 14 3 15.3431 3 17V18C3 19.6569 4.34315 21 6 21H18C19.6569 21 21 19.6569 21 18V17C21 15.3431 19.6569 14 18 14Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "shield.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 8V13.9098C4 15.8037 5.07001 17.535 6.76393 18.382L9.76393 19.882C11.1716 20.5858 12.8284 20.5858 14.2361 19.882L17.2361 18.382C18.93 17.535 20 15.8037 20 13.9098V8C20 5.23858 17.7614 3 15 3H9C6.23858 3 4 5.23858 4 8Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  "shield.lock.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M15 2C18.3137 2 21 4.68629 21 8V13.9102C20.9999 16.1826 19.7161 18.26 17.6836 19.2764L14.6836 20.7764C12.9944 21.621 11.0056 21.621 9.31641 20.7764L6.31641 19.2764C4.28395 18.26 3.00012 16.1826 3 13.9102V8C3 4.68629 5.68629 2 9 2H15ZM12 6C9.79086 6 8 7.79086 8 10V10.2695C7.40267 10.6155 7 11.2601 7 12V14C7 15.1046 7.89543 16 9 16H15C16.1046 16 17 15.1046 17 14V12C17 11.2601 16.5973 10.6155 16 10.2695V10C16 7.79086 14.2091 6 12 6ZM12 8C13.1046 8 14 8.89543 14 10H10C10 8.89543 10.8954 8 12 8Z",
        fill: "on",
      },
    ],
  },
  "shield.lock": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 8V13.9098C4 15.8037 5.07001 17.535 6.76393 18.382L9.76393 19.882C11.1716 20.5858 12.8284 20.5858 14.2361 19.882L17.2361 18.382C18.93 17.535 20 15.8037 20 13.9098V8C20 5.23858 17.7614 3 15 3H9C6.23858 3 4 5.23858 4 8Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M15 15H9C8.44772 15 8 14.5523 8 14V12C8 11.4477 8.44772 11 9 11H15C15.5523 11 16 11.4477 16 12V14C16 14.5523 15.5523 15 15 15Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
      {
        type: "path",
        d: "M9 11V10C9 8.34315 10.3431 7 12 7C13.6569 7 15 8.34315 15 10V11",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  shield: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 8V13.9098C4 15.8037 5.07001 17.535 6.76393 18.382L9.76393 19.882C11.1716 20.5858 12.8284 20.5858 14.2361 19.882L17.2361 18.382C18.93 17.535 20 15.8037 20 13.9098V8C20 5.23858 17.7614 3 15 3H9C6.23858 3 4 5.23858 4 8Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "sparkle.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M8.26468 9.31514L4.14467 11.0809C3.33656 11.4272 3.33657 12.5728 4.14467 12.9191L8.26468 14.6849C8.73671 14.8872 9.11284 15.2633 9.31514 15.7353L11.0809 19.8553C11.4272 20.6634 12.5728 20.6634 12.9191 19.8553L14.6849 15.7353C14.8872 15.2633 15.2633 14.8872 15.7353 14.6849L19.8553 12.9191C20.6634 12.5728 20.6634 11.4272 19.8553 11.0809L15.7353 9.31514C15.2633 9.11284 14.8872 8.73671 14.6849 8.26468L12.9191 4.14467C12.5728 3.33656 11.4272 3.33657 11.0809 4.14467L9.31514 8.26468C9.11284 8.73671 8.73671 9.11284 8.26468 9.31514Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  sparkle: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M8.26468 9.31514L4.14467 11.0809C3.33656 11.4272 3.33657 12.5728 4.14467 12.9191L8.26468 14.6849C8.73671 14.8872 9.11284 15.2633 9.31514 15.7353L11.0809 19.8553C11.4272 20.6634 12.5728 20.6634 12.9191 19.8553L14.6849 15.7353C14.8872 15.2633 15.2633 14.8872 15.7353 14.6849L19.8553 12.9191C20.6634 12.5728 20.6634 11.4272 19.8553 11.0809L15.7353 9.31514C15.2633 9.11284 14.8872 8.73671 14.6849 8.26468L12.9191 4.14467C12.5728 3.33656 11.4272 3.33657 11.0809 4.14467L9.31514 8.26468C9.11284 8.73671 8.73671 9.11284 8.26468 9.31514Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "square.and.arrow.right.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16.1257 16.1252C16.1257 18.3342 14.3346 20.125 12.1257 20.1252L6.12566 20.1252C3.91652 20.1252 2.12566 18.3344 2.12566 16.1252V8.12522C2.12566 5.91608 3.91652 4.12522 6.12566 4.12522H12.1257C14.3346 4.12548 16.1257 5.91624 16.1257 8.12522V11.1252L8.12469 11.1252C7.57271 11.1255 7.12481 11.5732 7.12469 12.1252C7.1248 12.6772 7.5727 13.125 8.12469 13.1252L16.1257 13.1252V16.1252ZM21.4743 10.925C22.0076 11.6361 22.0076 12.6143 21.4743 13.3254L18.9245 16.7248C18.5931 17.1663 17.9668 17.2562 17.5251 16.925C17.0837 16.5937 16.994 15.9673 17.3249 15.5256L19.1257 13.1252H16.1257V11.1252H19.1257L17.3249 8.72483C16.994 8.28313 17.0837 7.65675 17.5251 7.32542C17.9668 6.99425 18.5931 7.08405 18.9245 7.52561L21.4743 10.925Z",
        fill: "on",
      },
    ],
  },
  "square.and.arrow.right": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M14.6254 8.7087V7.62537C14.6254 5.96851 13.2822 4.62537 11.6254 4.62537L5.62537 4.62537C3.96851 4.62537 2.62537 5.96851 2.62537 7.62537L2.62537 15.6254C2.62537 17.2822 3.96851 18.6254 5.62537 18.6254H11.6254C13.2822 18.6254 14.6254 17.2822 14.6254 15.6254V14.542",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M20.9747 10.4247C21.508 11.1357 21.5079 12.114 20.9747 12.8251L18.4249 16.2245C18.0936 16.6663 17.4673 16.7559 17.0255 16.4247C16.5841 16.0933 16.4942 15.467 16.8253 15.0253L18.6261 12.6249L7.62509 12.6249C7.07293 12.6247 6.62509 12.1771 6.62509 11.6249C6.62534 11.0729 7.07309 10.625 7.62509 10.6249L18.6261 10.6249L16.8253 8.2245C16.4944 7.7827 16.5838 7.15631 17.0255 6.82509C17.4672 6.49401 18.0935 6.5839 18.4249 7.02528L20.9747 10.4247Z",
        fill: "on",
      },
    ],
  },
  "square.and.arrow.up.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 7.99952C18.209 7.99952 19.9997 9.7906 20 11.9995V17.9995C20 20.2087 18.2091 21.9995 16 21.9995H8C5.79086 21.9995 4 20.2087 4 17.9995V11.9995C4.00026 9.7906 5.79102 7.99952 8 7.99952H11V16.0005C11.0003 16.5525 11.448 17.0004 12 17.0005C12.552 17.0004 12.9997 16.5525 13 16.0005V7.99952H16ZM10.7998 2.65089C11.5109 2.11758 12.4891 2.1176 13.2002 2.65089L16.5996 5.2007C17.0411 5.53209 17.131 6.15839 16.7998 6.60011C16.4685 7.04149 15.8421 7.13119 15.4004 6.8003L13 4.99952V7.99952H11V4.99952L8.59961 6.8003C8.15791 7.13124 7.53152 7.04153 7.2002 6.60011C6.86903 6.15837 6.95883 5.53207 7.40039 5.2007L10.7998 2.65089Z",
        fill: "on",
      },
    ],
  },
  "square.and.arrow.up": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M9.08333 9H8C6.34314 9 5 10.3431 5 12V18C5 19.6569 6.34315 21 8 21H16C17.6569 21 19 19.6569 19 18V12C19 10.3431 17.6569 9 16 9H14.9167",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M10.8 2.65019C11.5111 2.11702 12.4894 2.11691 13.2004 2.65019L16.5998 5.19999C17.0415 5.53127 17.131 6.15761 16.8 6.5994C16.4687 7.04117 15.8424 7.1308 15.4006 6.7996L13.0002 4.99882V15.9998C13.0002 16.552 12.5524 16.9997 12.0002 16.9998C11.4479 16.9998 11.0002 16.5521 11.0002 15.9998V4.99882L8.5998 6.7996C8.15798 7.13083 7.53172 7.04118 7.20039 6.5994C6.86918 6.15758 6.95882 5.53131 7.40058 5.19999L10.8 2.65019Z",
        fill: "on",
      },
    ],
  },
  "star.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M10.583 5.68027C11.0354 4.37897 12.8327 4.33826 13.3691 5.5582L13.417 5.68027L14.5967 9.07481L18.1904 9.14902C19.6122 9.178 20.1994 10.9841 19.0664 11.8434L16.2021 14.0143L17.2432 17.4557C17.655 18.8169 16.1176 19.934 14.9502 19.1217L12 17.068L9.0498 19.1217C7.88244 19.934 6.34501 18.8169 6.75684 17.4557L7.79688 14.0143L4.93359 11.8434C3.80061 10.9841 4.38778 9.178 5.80957 9.14902L9.40234 9.07481L10.583 5.68027Z",
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
    ],
  },
  star: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M10.583 5.68027C11.0354 4.37897 12.8327 4.33826 13.3691 5.5582L13.417 5.68027L14.5967 9.07481L18.1904 9.14902C19.6122 9.178 20.1994 10.9841 19.0664 11.8434L16.2021 14.0143L17.2432 17.4557C17.655 18.8169 16.1176 19.934 14.9502 19.1217L12 17.068L9.0498 19.1217C7.88244 19.934 6.34501 18.8169 6.75684 17.4557L7.79688 14.0143L4.93359 11.8434C3.80061 10.9841 4.38778 9.178 5.80957 9.14902L9.40234 9.07481L10.583 5.68027Z",
        strokeWidth: 2,
        stroke: "on",
      },
    ],
  },
  "trash.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M14 2.05566C16.3083 2.05566 17.9999 4.10529 18 6.39941V6.51367H20C20.5522 6.51367 20.9998 6.96153 21 7.51367C21 8.06596 20.5523 8.51367 20 8.51367H18.9277L18.2266 17.8975C18.0647 20.0592 16.4111 21.8887 14.2393 21.8887H9.76074C7.58893 21.8887 5.93526 20.0592 5.77344 17.8975L5.07227 8.51367H4C3.44772 8.51367 3 8.06596 3 7.51367C3.00016 6.96153 3.44782 6.51367 4 6.51367H6V6.39941C6.00006 4.10529 7.69166 2.05566 10 2.05566H14ZM10 9.85742C9.44778 9.85742 9.00011 10.3052 9 10.8574V17.5449C9.00011 18.0971 9.44778 18.5449 10 18.5449C10.5522 18.5449 10.9999 18.0971 11 17.5449V10.8574C10.9999 10.3052 10.5522 9.85742 10 9.85742ZM14 9.85742C13.4478 9.85742 13.0001 10.3052 13 10.8574V17.5449C13.0001 18.0971 13.4478 18.5449 14 18.5449C14.5522 18.5449 14.9999 18.0971 15 17.5449V10.8574C14.9999 10.3052 14.5522 9.85742 14 9.85742ZM10 4.05566C8.99469 4.05566 8.00005 5.00036 8 6.39941V6.51367H16V6.39941C15.9999 5.00036 15.0053 4.05566 14 4.05566H10Z",
        fill: "on",
      },
    ],
  },
  trash: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M18 7.5L17.2292 17.9053C17.0996 19.6545 15.7998 21 14.2396 21H9.76036C8.20009 21 6.90029 19.6545 6.77072 17.9053L6 7.5M18 7.5H20M18 7.5H6M6 7.5H4M17 7.5V6.375C17 4.51104 15.6569 3 14 3H10C8.34315 3 7 4.51104 7 6.375V7.5",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M10 11V17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
      {
        type: "path",
        d: "M14 11V17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "tray.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M17.6455 5C18.8722 5 19.9761 5.74677 20.4316 6.88574L21.7852 10.2705C21.9269 10.6248 21.9999 11.0032 22 11.3848V16C22 17.6569 20.6569 19 19 19H5C3.34315 19 2 17.6569 2 16V11.3848C2.00005 11.0032 2.07315 10.6247 2.21484 10.2705L3.56836 6.88574C4.02395 5.74677 5.12778 5 6.35449 5H17.6455ZM7 10C6.44772 10 6 10.4477 6 11C6 11.5523 6.44772 12 7 12H9.24805C9.44023 12.0001 9.60864 12.1283 9.66016 12.3135C10.3188 14.6846 13.6812 14.6846 14.3398 12.3135C14.3914 12.1283 14.5598 12.0001 14.752 12H17C17.5523 12 18 11.5523 18 11C18 10.4477 17.5523 10 17 10H14.752C13.6613 10.0001 12.705 10.7275 12.4131 11.7783C12.2969 12.1965 11.7031 12.1965 11.5869 11.7783C11.295 10.7275 10.3387 10.0001 9.24805 10H7Z",
        fill: "on",
      },
    ],
  },
  tray: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M19 18H5C3.89543 18 3 17.1046 3 16V11.3852C3 11.1307 3.04855 10.8786 3.14305 10.6424L4.49711 7.25722C4.80084 6.4979 5.53626 6 6.35407 6H17.6459C18.4637 6 19.1992 6.4979 19.5029 7.25722L20.857 10.6424C20.9515 10.8786 21 11.1307 21 11.3852V16C21 17.1046 20.1046 18 19 18Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M7 11H9.24776C9.88933 11 10.4522 11.4278 10.6239 12.046C11.0113 13.4406 12.9887 13.4406 13.3761 12.046C13.5478 11.4278 14.1107 11 14.7522 11H17",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "user.card.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M16 4C19.3137 4 22 6.68629 22 10V14C22 17.3137 19.3137 20 16 20H8C4.68629 20 2 17.3137 2 14V10C2 6.68629 4.68629 4 8 4H16ZM7.66699 12.5C6.47038 12.5 5.5 13.4704 5.5 14.667C5.50018 15.127 5.87303 15.4998 6.33301 15.5H11.667C12.127 15.4998 12.4998 15.127 12.5 14.667C12.5 13.4704 11.5296 12.5 10.333 12.5H7.66699ZM14 14.5C13.7239 14.5 13.5 14.7239 13.5 15C13.5 15.2761 13.7239 15.5 14 15.5H18C18.2761 15.5 18.5 15.2761 18.5 15C18.5 14.7239 18.2761 14.5 18 14.5H14ZM14 12.5C13.7239 12.5 13.5 12.7239 13.5 13C13.5 13.2761 13.7239 13.5 14 13.5H18C18.2761 13.5 18.5 13.2761 18.5 13C18.5 12.7239 18.2761 12.5 18 12.5H14ZM9 8.5C8.17157 8.5 7.5 9.17157 7.5 10C7.5 10.8284 8.17157 11.5 9 11.5C9.82843 11.5 10.5 10.8284 10.5 10C10.5 9.17157 9.82843 8.5 9 8.5ZM14 10.5C13.7239 10.5 13.5 10.7239 13.5 11C13.5 11.2761 13.7239 11.5 14 11.5H18C18.2761 11.5 18.5 11.2761 18.5 11C18.5 10.7239 18.2761 10.5 18 10.5H14Z",
        fill: "on",
      },
    ],
  },
  "user.card": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M3 10C3 7.23858 5.23858 5 8 5H16C18.7614 5 21 7.23858 21 10V14C21 16.7614 18.7614 19 16 19H8C5.23858 19 3 16.7614 3 14V10Z",
        strokeWidth: 2,
        stroke: "on",
      },
      {
        type: "path",
        d: "M10.3333 13H7.66667C6.74619 13 6 13.7462 6 14.6667C6 14.8508 6.14924 15 6.33333 15H11.6667C11.8508 15 12 14.8508 12 14.6667C12 13.7462 11.2538 13 10.3333 13Z",
        strokeLinecap: "round",
        fill: "on",
        stroke: "on",
      },
      { type: "circle", cx: 9, cy: 10, r: 1, fill: "on", stroke: "on" },
      {
        type: "path",
        d: "M14 11H18M14 13H18M14 15H18",
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "user.fill": {
    knockout: false,
    elements: [
      {
        type: "circle",
        cx: 12,
        cy: 8,
        r: 3,
        strokeWidth: 2,
        fill: "on",
        stroke: "on",
      },
      {
        type: "path",
        d: "M18.7169 19L5.28309 19C4.72218 19 4.37849 18.385 4.67247 17.9072C8.03213 12.4478 15.9679 12.4478 19.3275 17.9072C19.6215 18.3849 19.2778 19 18.7169 19Z",
        strokeWidth: 2,
        strokeLinecap: "round",
        fill: "on",
        stroke: "on",
      },
    ],
  },
  user: {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 8, r: 3, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M4 19C7.08087 12.068 16.9191 12.068 20 19",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  "xmark.circle.fill": {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3ZM15.707 8.29297C15.3165 7.90244 14.6835 7.90244 14.293 8.29297L12 10.5859L9.70703 8.29297C9.31651 7.90244 8.68349 7.90244 8.29297 8.29297C7.90244 8.68349 7.90244 9.31651 8.29297 9.70703L10.5859 12L8.29297 14.293C7.90244 14.6835 7.90244 15.3165 8.29297 15.707C8.68349 16.0976 9.31651 16.0976 9.70703 15.707L12 13.4141L14.293 15.707C14.6835 16.0976 15.3165 16.0976 15.707 15.707C16.0976 15.3165 16.0976 14.6835 15.707 14.293L13.4141 12L15.707 9.70703C16.0976 9.31651 16.0976 8.68349 15.707 8.29297Z",
        fill: "on",
      },
    ],
  },
  "xmark.circle": {
    knockout: false,
    elements: [
      { type: "circle", cx: 12, cy: 12, r: 8, strokeWidth: 2, stroke: "on" },
      {
        type: "path",
        d: "M9 9L15 15M9 15L15 9",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
  xmark: {
    knockout: false,
    elements: [
      {
        type: "path",
        d: "M4 4L20 20M4 20L20 4",
        strokeWidth: 2,
        strokeLinecap: "round",
        stroke: "on",
      },
    ],
  },
} satisfies Record<string, IconData>;

export type IconName = keyof typeof Icons;
