// Generated by scripts/generate-icons.mjs from assets/icons — do not edit.

import type { ImageSourcePropType } from "react-native";

/** PNG versions of the user's icons, for native toolbar buttons (tinted by the system) */
export const ToolbarIcons = {
  "line.3.horizontal": require("@/assets/icons/toolbar/line.3.horizontal.png"),
} satisfies Record<string, ImageSourcePropType>;

export type ToolbarIconName = keyof typeof ToolbarIcons;
